name: Mark_Classified
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.6.0+9

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  
  provider: ^6.0.3
  http: ^1.1.0
  html_unescape: ^2.0.0
  sqflite: ^2.1.0
  image_picker: ^1.0.4
  
  path: ^1.8.2
  firebase_auth: ^4.13.0
  cloud_firestore: ^4.9.3
  firebase_core: ^2.17.0
  firebase_messaging: ^14.0.0
  google_sign_in: ^6.1.6
  flutter_facebook_auth: ^6.0.2
  carousel_slider: ^4.1.1
  shared_preferences: ^2.0.15
  webview_flutter: ^4.4.2
  http_auth: ^1.0.1
  flutter_custom_tabs: ^1.0.4

  # multi_image_picker: ^4.8.1
  
  html: ^0.15.0
  google_maps_flutter: ^2.2.1
  photo_view: ^0.14.0
  url_launcher: ^6.1.6
  
  launch_review: ^3.0.1
  share: ^2.0.4
  flutter_staggered_grid_view: ^0.7.0
  
  facebook_audience_network: ^1.0.1
  
  fluttertoast: ^8.0.9
  intl: ^0.18.1
  
  
  
  file_picker: ^6.1.1
  loader_overlay: ^2.1.0
  infinite_scroll_pagination: ^4.0.0
  razorpay_flutter: ^1.3.2
  # payu_money_flutter: ^0.0.3
  flutterwave_standard: ^1.0.4
  package_info_plus: ^4.2.0
  crypto: ^3.0.1
  #package to restart the app when user sign in or out
  flutter_phoenix: ^1.1.0
  advertising_id: ^2.3.0
  flutter_local_notifications: ^16.1.0
  purchases_flutter: ^6.2.0
  app_tracking_transparency: ^2.0.3
  flutter_native_splash: ^2.3.5
  flutter_launcher_icons: ^0.13.1

  # flutter_paystack: ^1.0.6
  # native_admob_flutter: ^1.5.0+1
  # dio: ^4.0.6
  # cupertino_icons: ^1.0.5
  # flutter_absolute_path: ^1.0.6
  # multi_image_picker: ^4.8.1
  # android_intent: ^2.0.2
  #flutter_native_admob: ^2.1.0+3
  # google_mobile_ads: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  dependency_validator: ^3.2.3

dependency_overrides:
  # # fix `packageRoot`compile error for iOS, because `path_provider` is using an old version of `platform`
  # platform: ^3.0.0 # overrides `path_provider`


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/clickforsale.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash_loading.png