// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQOOFs7Y8XfcfgBid6oUeY3JkILXGjKg4',
    appId: '1:618858142282:web:327db16229e9068543a4b3',
    messagingSenderId: '618858142282',
    projectId: 'mark-classified',
    authDomain: 'mark-classified.firebaseapp.com',
    databaseURL: 'https://mark-classified-default-rtdb.firebaseio.com',
    storageBucket: 'mark-classified.appspot.com',
    measurementId: 'G-8YZHCN027G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo3lAWx77zEGDjLiKVLYgYTCEXGyqtWiU',
    appId: '1:618858142282:android:6437b4695d61671c43a4b3',
    messagingSenderId: '618858142282',
    projectId: 'mark-classified"',
    databaseURL: 'https://mark-classified-default-rtdb.firebaseio.com',
    storageBucket: 'mark-classified.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEDvNWD6fHE9yRcBClcKKyb0DC-pY56JU',
    appId: '1:618858142282:ios:601f7f429e99cee843a4b3',
    messagingSenderId: '618858142282',
    projectId: 'mark-classified',
    databaseURL: 'https://mark-classified-default-rtdb.firebaseio.com',
    storageBucket: 'mark-classified.appspot.com',
    androidClientId:
        '618858142282-0e78chvilfg8pfgrf8691tlerqsag5rb.apps.googleusercontent.com',
    iosClientId:
        '618858142282-1spr8lgdfch5336d4gin4i9j4pddblqf.apps.googleusercontent.com',
    iosBundleId: 'com.canderios.markclassified',
  );
}
